name: Deploy Go Application

on:
  push:
    branches:
      - dev  # Укажите ветку, при пуше в которую будет запускаться деплой
    tags:
      - 'v*'  # Деплой при создании тега, начинающегося с 'v' (например, v1.0.0)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build the application
        run: |
          go mod download
          go build -o ./bin/app ./cmd/main.go

      - name: Run tests
        run: go test ./...

      - name: Set up SSH key
        run: | 
          mkdir -p ~/.ssh 
          echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          echo "${{ secrets.DEV_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -T -i ~/.ssh/id_rsa ${{ secrets.DEV_SERVER_USER }}@${{ secrets.DEV_SERVER_IP }}

      - name: Deploy to server
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.DEV_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no ./bin/app ${{ secrets.DEV_SERVER_USER }}@${{ secrets.DEV_SERVER_IP }}:${{ secrets.DEV_DEPLOY_PATH }}

